sonar.projectKey=artemcherepanov2357_python-project-52
sonar.organization=artemcherepanov2357

sonar.sources=apps,task_manager
sonar.tests=.

sonar.test.inclusions=**/tests.py
sonar.python.coverage.reportPaths=coverage.xml

sonar.exclusions=**/migrations/**,**/settings.py,**/__init__.py,**/apps.py,**/admin.py