# Generated by Django 6.1.1 on 2026-09-19 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0002_alter_label_options_alter_label_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='label',
            options={'verbose_name': 'Task label', 'verbose_name_plural': 'Task labels'},
        ),
    ]
