# Generated by Django 6.1.1 on 2026-09-19 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statuses', '0002_alter_status_options_alter_status_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name': 'Task status', 'verbose_name_plural': 'Task statuses'},
        ),
    ]
